### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by danielscatigno-ncpc** [ChristopheLav/iis-deploy#2]
Hi, I'm trying to publish using this extension but nothing happens

I'm trying to publish a test with:

```

name: CapturaXML Build Production

on:
  push:
    branches: [ "LeituraCobrancas" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Create a offline file
      run: echo "" > app_offline.htm    
    - uses: ChristopheLav/iis-deploy@v1
      with:
        website-name: 'CapturaXML2'
        msdeploy-service-url: '192.1.1.1'
        msdeploy-username: 'publish'
        msdeploy-password: 'pasword123'
        source-path: '${{ github.workspace }}'
        
        
```
The info provided here is fictional
I've already tested it using Visual Studio
No errors are thrown
