### ISSUE TITLE
Strange, it didn't update any files and there were no errors

### ISSUE THREAD

**Issue by marciusbezerra** [ChristopheLav/iis-deploy#4]
I looked at the dates, the files still have the old dates, it's as if I hadn't updated anything, where were the files copied to?

If an error message occurred it would be easier

```
     # ... 
    - name: Publish
      run: dotnet publish ./MyApp/MyApp.csproj -c Release -o ./publish

    - uses: ChristopheLav/iis-deploy@v1
      with:
        website-name: ${{ secrets.SITE_NAME }} # this is my.app
        msdeploy-service-url: https://${{ secrets.SERVER_ADDRESS }}:8172 # this is a IP public
        msdeploy-username: ${{ secrets.USERNAME }} 
        msdeploy-password: ${{ secrets.PASSWORD }}
        source-path: ./publish
```
I also tried with...
`source-path: ${{ github.workspace }}\publish`
